az-configuration:
- name: ((az1))
- name: ((az2))
- name: ((az3))
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: ((az1))
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((infrastructure_subnet_ids_1))
      cidr: 10.0.16.0/28
      dns: 10.0.0.2
      gateway: 10.0.16.1
      reserved_ip_ranges: 10.0.16.0-10.0.16.4
      availability_zone_names:
      - ((az1))
    - iaas_identifier: ((infrastructure_subnet_ids_2))
      cidr: 10.0.16.16/28
      dns: 10.0.0.2
      gateway: 10.0.16.17
      reserved_ip_ranges: 10.0.16.16-10.0.16.20
      availability_zone_names:
      - ((az2))
    - iaas_identifier: ((infrastructure_subnet_ids_3))
      cidr: 10.0.16.32/28
      dns: 10.0.0.2
      gateway: 10.0.16.33
      reserved_ip_ranges: 10.0.16.32-10.0.16.36
      availability_zone_names:
      - ((az3))
  - name: pks
    subnets:
    - iaas_identifier: ((pcf_subnet_ids_1))
      cidr: 10.0.4.0/24
      dns: 10.0.0.2
      gateway: 10.0.4.1
      reserved_ip_ranges: 10.0.4.0-10.0.4.4
      availability_zone_names:
      - ((az1))
    - iaas_identifier: ((pcf_subnet_ids_2))
      cidr: 10.0.5.0/24
      dns: 10.0.0.2
      gateway: 10.0.5.1
      reserved_ip_ranges: 10.0.5.0-10.0.5.4
      availability_zone_names:
      - ((az2))
    - iaas_identifier: ((pcf_subnet_ids_3))
      cidr: 10.0.6.0/24
      dns: 10.0.0.2
      gateway: 10.0.6.1
      reserved_ip_ranges: 10.0.6.0-10.0.6.4
      availability_zone_names:
      - ((az3))
  - name: services
    subnets:
    - iaas_identifier: ((services_subnet_ids_1))
      cidr: 10.0.8.0/24
      dns: 10.0.0.2
      gateway: 10.0.8.1
      reserved_ip_ranges: 10.0.8.0-10.0.8.3
      availability_zone_names:
      - ((az1))
    - iaas_identifier: ((services_subnet_ids_2))
      cidr: 10.0.9.0/24
      dns: 10.0.0.2
      gateway: 10.0.9.1
      reserved_ip_ranges: 10.0.9.0-10.0.9.3
      availability_zone_names:
      - ((az2))
    - iaas_identifier: ((services_subnet_ids_3))
      cidr: 10.0.10.0/24
      dns: 10.0.0.2
      gateway: 10.0.10.1
      reserved_ip_ranges: 10.0.10.0-10.0.10.3
      availability_zone_names:
      - ((az3))
properties-configuration:
  director_configuration:
    allow_legacy_agents: false
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: 0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org,
      3.amazon.pool.ntp.org
    post_deploy_enabled: false
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: true
  dns_configuration:
    handlers: []
  iaas_configuration:
    encrypted: false
    ssh_private_key: ((ssh_private_key))
    iam_instance_profile: ((ops_manager_iam_instance_profile_name))
    key_pair_name: ((ops_manager_ssh_public_key_name))
    region: ((region))
    security_group: ((vms_security_group_id))
  security_configuration:
    generate_vm_passwords: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []
