product-name: cf
network-properties:
  singleton_availability_zone:
    name: eu-west-2
  other_availability_zones:
  - name: eu-west-2a
  - name: eu-west-2b
  - name: eu-west-2c
  network:
    name: pas
product-properties:
  .cloud_controller.system_domain:
    value: sys.((subdomain-name)).((domain-name))
  .cloud_controller.apps_domain:
    value: apps.((subdomain-name)).((domain-name))
  .properties.networking_poe_ssl_certs:
    value:
    - name: certificate
      certificate:
        cert_pem: ((domain-crt))
        private_key_pem: ((domain-key))
  .properties.haproxy_forward_tls:
    value: disable
  .ha_proxy.skip_cert_verify:
    value: true
  .properties.security_acknowledgement:
    value: X
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: ((domain-crt))
      private_key_pem: ((domain-key))
  .properties.credhub_key_encryption_passwords:
    value:
    - name: default
      key:
        secret: ((om-password))
      primary: true
  .mysql_monitor.recipient_email:
    value: anything@pivotal.io
errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: false
  deploy-notifications-ui:
    post-deploy-state: false
  nfsbrokerpush:
    post-deploy-state: false
  test-autoscaling:
    post-deploy-state: true
resource-config:
  compute:
    instances: 3
    instance_type:
      id: 2xlarge.disk
  control:
    elb_names:
    - tcp:((subdomain-name))-cf-ssh
  router:
    elb_names:
    - tcp:((subdomain-name))-cf-ws
    - http:((subdomain-name))-httpslb
